export default {
  "overview": "Overview",
  "editor": "Rich Text Editor",
  "wiki-links": "Wiki Links & Backlinks",
  "graph": "Graph Visualization",
  "canvas": "Canvas & Whiteboard",
  "search": "Search & Discovery",
  "tasks": "Task Management & Kanban",
  "bases": "Bases (Database Views)",
  "templates": "Templates",
  "plugins": "Plugin System",
  "multimedia-library": "Multimedia Library (Experimental)",
  "image-viewer": "Image Viewer",
  "gmail": "Gmail Integration",
  "themes": "Themes & Customization",
  "file-management": "File Management",
  "workspace": "Workspace",
  "command-palette": "Command Palette",
  "keyboard-shortcuts": "Keyboard Shortcuts",
  "settings": "Settings",
  "auto-updater": "Automatic Updates",
  "remote-config": "Remote Configuration",
  "import-export": "Import & Export",
  "folders-tags": "Folders & Tags",
  "markdown": "Markdown",
  "automation": "Automation"
}